### ISSUE TITLE
Support wildfiy 10 ?

### ISSUE THREAD

**Issue by slieer** [snowdrop/snowdrop#34]
Supports wildfiy?　Projects also have maintenance? Spring is very widely used. Please try to support. Thank you !

**Comment by joshuawilson** [comment]
Snowdrop was needed to connect much older versions of JBoss and Spring. Both projects have evolved to a point that they just work. If you find a specific issue with running Spring on WildFly, you can list that. However, this project (Snowdrop) is no longer being working on. If you want to work on it, make a wildfly10 branch and i'll accept PRs.

**Comment by slieer** [comment]
Oh, oh,  Thanks very much.
